=== conuti-gmbh/bo4e-schema-en/schemas/v1/bo/AdHocControlChannel.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema/master/schemas/v1/bo/AdHocSteuerkanal.schema.json",
  "title": "AdHocControlChannel",
  "type": "object",
  "properties": {
    "boType": {
      "$ref": "../enum/BOType.schema.json",
      "default": "AD_HOC_CONTROL_CHANNEL"
    },
    "structureVersion": {
      "type": "string",
      "default": "1",
      "description": "versionStruktur"
    },
    "configurationProduct": {
      "type": "string",
      "faker": {
        "string.numeric": 14
      },
      "description": "konfigurationsprodukt"
    },
    "targetAddress": {
      "$ref": "../com/TargetAddress.schema.json"
    },
    "issuer": {
      "$ref": "../com/Issuer.schema.json"
    },
    "certificateUser": {
      "$ref": "../com/CertificateUser.schema.json"
    },
    "IpAddressClsDevice": {
      "$ref": "../com/IpAddressClsDevice.schema.json"
    }
  },
  "required": [
    "boType",
    "structureVersion"
  ]
}

=== conuti-gmbh/bo4e-schema-en/docs/examples/bo/AdHocControlChannel.json
{
  "boType": "AD_HOC_CONTROL_CHANNEL",
  "structureVersion": "1",
  "configurationProduct": "33101747933462",
  "targetAddress": {
    "targetAddress1": "fugiat Duis",
    "targetAddress2": "eiusmod non pariatur sit",
    "targetAddress3": "exercitation quis laborum fugiat elit",
    "targetAddress4": "qui ad irure nisi mollit",
    "targetAddress5": "qui"
  },
  "issuer": {
    "issuer1": "magna in tempor",
    "issuer2": "Ut",
    "issuer3": "consectetur proident sed ad officia",
    "issuer4": "id",
    "issuer5": "culpa incididunt quis"
  },
  "certificateUser": {
    "certificateUser1": "ad enim ex aliqua elit",
    "certificateUser2": "tempor laborum non dolore",
    "certificateUser3": "dolor",
    "certificateUser4": "id nulla culpa",
    "certificateUser5": "consectetur dolor"
  },
  "IpAddressClsDevice": {
    "IpAddressClsDevice1": "in labore",
    "IpAddressClsDevice2": "eu magna",
    "IpAddressClsDevice3": "dolore ut consequat Lorem qui",
    "IpAddressClsDevice4": "consectetur dolore",
    "IpAddressClsDevice5": "sint laborum ex aliqua elit"
  }
}
