=== conuti-gmbh/bo4e-schema-en/schemas/v1/bo/DisconnectionOrder.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema/master/schemas/v1/bo/Sperraufrag.schema.json",
  "title": "DisconnectionOrder",
  "type": "object",
  "properties": {
    "boType": {
      "$ref": "../enum/BOType.schema.json",
      "default": "DISCONNECTION_ORDER"
    },
    "structureVersion": {
      "type": "string",
      "default": "1",
      "description": "versionStruktur"
    },
    "meetingPoint": {
      "$ref": "../com/Address.schema.json"
    },
    "disconnectionOrderType": {
      "$ref": "../enum/DisconnectionOrderType.schema.json",
      "description": "Handelt es sich um einen Auftrag zum SPERREN oder ENTSPERREN?"
    },
    "disconnectionOrderStatus": {
      "$ref": "../enum/OrderStatus.schema.json",
      "description": "Auftragsstatus"
    },
    "disconnectionOrderRejectionReason": {
      "$ref": "../enum/DisconnectionOrderRejectionReason.schema.json",
      "description": "Falls Sperrauftragsstatus = ABGELEHNT"
    },
    "disconnectionPreventionReason": {
      "$ref": "../enum/DisconnectionPreventionReason.schema.json",
      "description": "Falls Sperrauftragsstatus = GESCHEITERT"
    },
    "meterNumber": {
      "type": "string",
      "faker": {
        "string.binary": {
          "prefix": "ZAEHLER_",
          "length": 6
        }
      },
      "description": "Die Nummer des zu sperrenden Zählers"
    },
    "isOrderedByBailiff": {
      "type": "boolean",
      "description": "True, falls die Sperrung vom Gerichtsvollzieher angeordnet ist."
    }
  },
  "required": [
    "boType",
    "structureVersion"
  ]
}

=== conuti-gmbh/bo4e-schema-en/docs/examples/bo/DisconnectionOrder.json
{
  "boType": "DISCONNECTION_ORDER",
  "structureVersion": "1",
  "meetingPoint": {
    "postalCode": "64677",
    "city": "Neu Kira",
    "street": "Regensburger Str.",
    "houseNumber": "3",
    "poBox": "qui exercitation laboris",
    "addressSupplement": "sunt ex",
    "coSupplement": "ipsum cillum sed",
    "countryCode": "VU",
    "district": "Wilhelmshaven",
    "additionalInformation": {
      "supplement1": "voluptate incididunt pariatur non do",
      "supplement2": "sunt dolore",
      "supplement3": "deserunt sed",
      "supplement4": "sed nisi",
      "supplement5": "ut nulla veniam"
    }
  },
  "disconnectionOrderType": "UNLOCK",
  "disconnectionOrderStatus": "AGREED",
  "disconnectionOrderRejectionReason": "OTHER_ERROR",
  "disconnectionPreventionReason": "TECHNICAL_PREVENTION_REASON",
  "meterNumber": "ZAEHLER_111011",
  "isOrderedByBailiff": false
}
