=== conuti-gmbh/bo4e-schema-en/schemas/v1/bo/LocationBundle.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema-en/main/schemas/v1/bo/LocationBundle.schema.json",
  "title": "LocationBundle",
  "type": "object",
  "properties": {
    "boType": {
      "$ref": "../enum/BOType.schema.json",
      "default": "LOCATION_BUNDLE"
    },
    "structureVersion": {
      "type": "string",
      "default": "1"
    },
    "locationBundleStructureId": {
      "type": "string",
      "faker": {
        "string.numeric": 11
      }
    },
    "locationBundleNumber": {
      "type": "integer"
    },
    "standardizedLocationBundleStructure": {
      "type": "boolean"
    },
    "dataQuality": {
      "$ref": "../enum/DataQuality.schema.json"
    },
    "validityPeriod": {
      "$ref": "../com/TimePeriod.schema.json"
    },
    "assignmentObjectCode": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "../com/AssignmentObjectCode.schema.json"
      }
    }
  },
  "required": [
    "boType",
    "structureVersion"
  ]
}

=== conuti-gmbh/bo4e-schema-en/docs/examples/bo/LocationBundle.json
{
  "boType": "LOCATION_BUNDLE",
  "structureVersion": "1",
  "locationBundleStructureId": "03606523785",
  "locationBundleNumber": 80912307,
  "standardizedLocationBundleStructure": false,
  "dataQuality": "NO_DATA_EXPECTED",
  "validityPeriod": {
    "timeUnit": "QUARTER_HOUR",
    "duration": 0,
    "startDate": "1895-09-01T16:37:08.0Z",
    "endDate": "1903-12-14T22:54:38.0Z",
    "unit": "HOUR",
    "readingPeriod": "972638",
    "billingPeriod": "174399",
    "periodText": "ullamco",
    "periodId": 9
  },
  "assignmentObjectCode": [
    {
      "referenceLocationType": "MALO",
      "referenceLocationId": "38328496354",
      "upstreamLocationType": "MALO",
      "upstreamLocationId": "60214676319",
      "objectCode": [
        {
          "objectCode": "CODE_101011",
          "locationBundleNumber": 10
        }
      ],
      "referenceMarketLocationTechnicalResource": [
        "82683650808"
      ]
    }
  ]
}
