=== conuti-gmbh/bo4e-schema-en/schemas/v1/bo/MarketParticipant.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema-en/main/schemas/v1/bo/MarketParticipant.schema.json",
  "title": "MarketParticipant",
  "type": "object",
  "properties": {
    "boType": {
      "$ref": "../enum/BOType.schema.json",
      "default": "MARKET_PARTICIPANT"
    },
    "structureVersion": {
      "type": "string",
      "default": "1"
    },
    "businessPartnerRole": {
      "$ref": "../enum/BusinessPartnerRole.schema.json"
    },
    "salutation": {
      "type": "string",
      "faker": "person.prefix"
    },
    "name1": {
      "type": "string",
      "faker": "person.lastName"
    },
    "name2": {
      "type": "string",
      "faker": "person.firstName"
    },
    "name3": {
      "type": "string"
    },
    "name4": {
      "type": "string"
    },
    "partnerAddress": {
      "$ref": "../com/Address.schema.json"
    },
    "commercialClassification": {
      "type": "boolean"
    },
    "externalCustomerNumberSupplier": {
      "type": "string"
    },
    "marketRole": {
      "$ref": "../enum/MarketRole.schema.json"
    },
    "roleCodeNumber": {
      "type": "string",
      "faker": {
        "string.numeric": 9
      }
    },
    "roleCodeType": {
      "$ref": "../enum/RoleCodeType.schema.json"
    },
    "vatId": {
      "type": "string",
      "faker": {
        "string.binary": {
          "prefix": "DE",
          "length": 9
        }
      }
    },
    "taxNumber": {
      "type": "string",
      "faker": {
        "string.numeric": 9
      }
    },
    "contactPerson": {
      "$ref": "../bo/ContactPerson.schema.json"
    },
    "makoAddress": {
      "type": "string"
    },
    "certificateDownloadLink": {
      "type": "string",
      "faker": "internet.url"
    },
    "courtOfRegistration": {
      "type": "string",
      "faker": "location.city"
    },
    "commercialRegisterNumber": {
      "type": "string",
      "faker": {
        "string.numeric": 6
      }
    },
    "website": {
      "type": "string",
      "faker": "internet.url"
    },
    "faxNumber": {
      "type": "string",
      "faker": "phone.number"
    },
    "communicationRole": {
      "$ref": "../enum/CommunicationRole.schema.json"
    },
    "subContracted": {
      "type": "boolean"
    },
    "communicationParameters": {
      "$ref": "../com/CommunicationParameters.schema.json"
    },
    "meteringPointOperatorAttribute": {
      "$ref": "../enum/MSBAttribute.schema.json"
    },
    "bankAccount": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "../com/BankAccount.schema.json"
      }
    },
    "reachability": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "../com/Reachability.schema.json"
      }
    },
    "ipAddress": {
      "type": "string",
      "faker": "internet.ip"
    },
    "ipRange": {
      "$ref": "../com/IpRange.schema.json"
    },
    "assignmentFrom": {
      "type": "string",
      "format": "date-time"
    },
    "assignmentTo": {
      "type": "string",
      "format": "date-time"
    },
    "balancingGroup": {
      "type": "string"
    },
    "balancingGroupPurpose": {
      "$ref": "../enum/BalancingGroupPurpose.schema.json"
    },
    "balancingGroups": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "../bo/BalancingGroup.schema.json"
      }
    }
  },
  "required": [
    "boType",
    "structureVersion"
  ]
}

=== conuti-gmbh/bo4e-schema-en/docs/examples/bo/MarketParticipant.json
{
  "boType": "MARKET_PARTICIPANT",
  "structureVersion": "1",
  "businessPartnerRole": "OWNER",
  "salutation": "Prof. Dr.",
  "name1": "Niedermeier",
  "name2": "Joseph",
  "name3": "commodo dolor est sed",
  "name4": "non",
  "partnerAddress": {
    "postalCode": "63782",
    "city": "Neumünster",
    "street": "Kämper Weg",
    "houseNumber": "76b",
    "poBox": "mollit eu cillum deserunt laboris",
    "addressSupplement": "esse laboris proident amet",
    "coSupplement": "irure reprehenderit qui nostrud",
    "countryCode": "LC",
    "district": "Alt Fine",
    "additionalInformation": {
      "supplement1": "amet in veniam",
      "supplement2": "dolor id eiusmod qui",
      "supplement3": "velit exercitation tempor",
      "supplement4": "in eiusmod enim",
      "supplement5": "nostrud veniam ullamco exercitation"
    }
  },
  "commercialClassification": true,
  "externalCustomerNumberSupplier": "nostrud est esse",
  "marketRole": "NB",
  "roleCodeNumber": "120915261",
  "roleCodeType": "GS1",
  "vatId": "DE110001011",
  "taxNumber": "314310327",
  "contactPerson": {
    "boType": "CONTACT_PERSON",
    "structureVersion": "1",
    "lastName": "Illing",
    "eMailAddress": "Mads.Helpling41@hotmail.com",
    "phoneNumbers": [
      {
        "numberType": "FAX_CENTRAL",
        "phoneNumber": "(0240) 907673487"
      }
    ]
  },
  "makoAddress": "id commodo",
  "certificateDownloadLink": "https://wunderhubsch-virus.org/",
  "courtOfRegistration": "Süd Iven",
  "commercialRegisterNumber": "772273",
  "website": "https://spritzig-elefant.name/",
  "faxNumber": "+49-5273-73095345",
  "communicationRole": "BILLING_PROCESSES",
  "subContracted": false,
  "communicationParameters": {
    "targetAddress": {
      "targetAddress1": "occaecat ullamco cupidatat exercitation Ut",
      "targetAddress2": "voluptate ex",
      "targetAddress3": "Lorem dolor enim",
      "targetAddress4": "nisi officia",
      "targetAddress5": "in aliqua irure"
    },
    "certificateIssuer": {
      "certificateIssuer1": "proident Ut veniam",
      "certificateIssuer2": "minim ut",
      "certificateIssuer3": "sit est",
      "certificateIssuer4": "ea in enim voluptate",
      "certificateIssuer5": "esse eu et cillum"
    },
    "certificateUser": {
      "certificateUser1": "irure tempor",
      "certificateUser2": "nisi ullamco consectetur Duis in",
      "certificateUser3": "Ut magna elit dolore",
      "certificateUser4": "velit sint",
      "certificateUser5": "est dolor aliqua cillum"
    }
  },
  "meteringPointOperatorAttribute": "DEFAULT_METERING_POINT_OPERATOR",
  "bankAccount": [
    {
      "purposeOfUse": "BV_PAYMENT_MMMA",
      "iban": "GT219296845A4122535042A1087R",
      "accountHolder": "Frau Janne Frey",
      "bic": "EYAVPFJMXXX",
      "creditInstitution": "Kampf Gruppe"
    }
  ],
  "reachability": [
    {
      "availability": "THURSDAY",
      "time": "et adipisicing"
    }
  ],
  "ipAddress": "38.253.21.31",
  "ipRange": {
    "lowerLimit": "edaa:ba87:bf4d:b5ea:fda7:ee3e:4c6c:8736",
    "upperLimit": "da42:6665:2d2e:20be:f4b0:cddc:1e36:b7b8"
  },
  "assignmentFrom": "1894-04-15T10:42:51.0Z",
  "assignmentTo": "1915-10-04T21:18:17.0Z",
  "balancingGroup": "do fugiat",
  "balancingGroupPurpose": "GENERATING_MARKET_LOCATION_CHP",
  "balancingGroups": [
    {
      "boType": "BALANCING_GROUP",
      "structureVersion": "1",
      "designation": "magna fugiat aliquip eu",
      "priority": 4,
      "balancingGroupPurpose": "CONSUMING_MARKET_LOCATION"
    }
  ]
}
