=== conuti-gmbh/bo4e-schema-en/schemas/v1/bo/MeteringTimeDefinition.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema/master/schemas/v1/bo/Zaehlzeitdefinition.schema.json",
  "title": "MeteringTimeDefinition",
  "type": "object",
  "properties": {
    "boType": {
      "$ref": "../enum/BOType.schema.json",
      "default": "METERING_TIME_DEFINITION"
    },
    "structureVersion": {
      "type": "string",
      "default": "1",
      "description": "versionStruktur"
    },
    "beginDate": {
      "type": "string",
      "format": "date-time",
      "description": "Der inklusive Zeitpunkt ab dem die Zaehlzeitdefinitionen ausgerollt sind"
    },
    "closingDate": {
      "type": "string",
      "format": "date-time",
      "description": "Der exklusive Zeitpunkt bis zu dem die Zaehlzeitdefinitionen ausgerollt sind"
    },
    "version": {
      "type": "string",
      "format": "date-time",
      "description": "Version der Zählzeitdefinition als Datum"
    },
    "necessity": {
      "$ref": "../enum/DefinitionsNecessity.schema.json",
      "description": "Beschreibt ob eine Zaehlzeitdefinitionen notwendig ist"
    },
    "versionSpecification": {
      "type": "string",
      "faker": {
        "string.binary": {
          "prefix": "VERSION_",
          "length": 6
        }
      },
      "description": "versionsangabe"
    },
    "code": {
      "type": "string",
      "faker": {
        "string.binary": {
          "prefix": "CODE_",
          "length": 6
        }
      },
      "description": "Zählzeitdefinition"
    },
    "meteringTimes": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "../com/MeteringTime.schema.json"
      },
      "description": "Liste der Zählzeiten [1 - 99999]"
    },
    "meteringTimeRegister": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "../com/MeteringTimeRegister.schema.json"
      },
      "description": "Liste der Zählzeitregister"
    }
  },
  "required": [
    "boType",
    "structureVersion"
  ]
}

=== conuti-gmbh/bo4e-schema-en/docs/examples/bo/MeteringTimeDefinition.json
{
  "boType": "METERING_TIME_DEFINITION",
  "structureVersion": "1",
  "beginDate": "1921-04-26T15:25:04.0Z",
  "closingDate": "1904-01-25T15:14:42.0Z",
  "version": "1896-09-06T21:55:07.0Z",
  "necessity": "DEFINITIONS_USED",
  "versionSpecification": "VERSION_000000",
  "code": "CODE_010111",
  "meteringTimes": [
    {
      "code": "CODE_101010",
      "frequency": "ANNUAL",
      "transmissibility": "NON_ELECTRONIC",
      "peakLoadDetermination": "USE_OF_PEAK_LOAD_WINDOW",
      "isOrderable": true,
      "typeValue": "OFF_PEAK_TIME_WINDOW",
      "descriptionType": "dolore in mollit",
      "changeTimestamp": "1931-07-11T21:13:23.0Z",
      "register": "ad laborum cupidatat ullamco veniam"
    }
  ],
  "meteringTimeRegister": [
    {
      "register": "deserunt enim",
      "meteringTimeDefinition": "magna aute consectetur",
      "offPeakCapable": "NOT_OFF_PEAK_CAPABLE"
    }
  ]
}
