=== conuti-gmbh/bo4e-schema-en/schemas/v1/bo/Offer.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema-en/main/schemas/v1/bo/Offer.schema.json",
  "title": "Offer",
  "type": "object",
  "properties": {
    "boType": {
      "$ref": "../enum/BOType.schema.json",
      "default": "OFFER"
    },
    "structureVersion": {
      "type": "string",
      "default": "1"
    },
    "offerNumber": {
      "type": "string",
      "faker": {
        "string.numeric": 3
      }
    },
    "requestReference": {
      "type": "string",
      "faker": {
        "string.binary": {
          "prefix": "REF",
          "length": 6
        }
      }
    },
    "offerDate": {
      "type": "string",
      "format": "date-time"
    },
    "sector": {
      "$ref": "../enum/Sector.schema.json"
    },
    "bindingPeriod": {
      "type": "string",
      "format": "date-time"
    },
    "offerGiver": {
      "$ref": "../bo/BusinessPartner.schema.json"
    },
    "offerRecipient": {
      "$ref": "../bo/BusinessPartner.schema.json"
    },
    "signatoryOfferRecipient": {
      "$ref": "../bo/ContactPerson.schema.json"
    },
    "signatoryOfferGiver": {
      "$ref": "../bo/ContactPerson.schema.json"
    },
    "setupTransmissionPeriod": {
      "$ref": "../com/TimePeriod.schema.json"
    },
    "offerBindingPeriod": {
      "$ref": "../com/TimePeriod.schema.json"
    },
    "variants": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "../com/OfferVariant.schema.json"
      }
    },
    "positionData": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "../com/OfferPosition.schema.json"
      }
    }
  },
  "required": [
    "boType",
    "structureVersion"
  ]
}

=== conuti-gmbh/bo4e-schema-en/docs/examples/bo/Offer.json
{
  "boType": "OFFER",
  "structureVersion": "1",
  "offerNumber": "464",
  "requestReference": "REF001001",
  "offerDate": "1896-09-06T01:21:40.0Z",
  "sector": "GAS",
  "bindingPeriod": "1968-05-23T11:59:54.0Z",
  "offerGiver": {
    "boType": "BUSINESS_PARTNER",
    "structureVersion": "1",
    "salutation": "Prof. Dr.",
    "name1": "Kneifel",
    "name2": "Mina",
    "name3": "Excepteur officia Ut",
    "name4": "eu ut",
    "vatId": "DE011101011",
    "creditorId": "009589",
    "emailAddress": "Dorian84@hotmail.com",
    "website": "https://hell-mars.org",
    "commercialClassification": true,
    "commercialRegisterNumber": "662404",
    "courtOfRegistration": "Bad Selmaland",
    "partnerAddress": {
      "postalCode": "11446",
      "city": "Miraland",
      "street": "Florianweg",
      "houseNumber": "76c",
      "poBox": "dolor eiusmod commodo",
      "addressSupplement": "aliqua",
      "coSupplement": "irure reprehenderit",
      "countryCode": "RS",
      "district": "Arnsberg",
      "additionalInformation": {
        "supplement1": "ad officia cupidatat reprehenderit consectetur",
        "supplement2": "ipsum",
        "supplement3": "est do officia",
        "supplement4": "ut ad",
        "supplement5": "do aute cillum Lorem sed"
      }
    },
    "externalCustomerNumberSupplier": "205967",
    "externalReferences": [
      {
        "externalReferenceName": "Kundennummer beim Lieferanten",
        "externalReferenceValue": "1401329340"
      }
    ],
    "businessPartnerRole": [
      "PROPERTY_MANAGER"
    ],
    "contactChannel": [
      "SMS"
    ],
    "contactPerson": {
      "boType": "CONTACT_PERSON",
      "structureVersion": "1",
      "lastName": "Thieke",
      "eMailAddress": "Allegra40@yahoo.com",
      "phoneNumbers": [
        {
          "numberType": "PHONE_EXTENSION",
          "phoneNumber": "+49-211-8464239"
        }
      ]
    }
  },
  "offerRecipient": {
    "boType": "BUSINESS_PARTNER",
    "structureVersion": "1",
    "salutation": "Prof. Dr.",
    "name1": "Bussmann",
    "name2": "Jona",
    "name3": "veniam nulla ex in qui",
    "name4": "in nisi nulla",
    "vatId": "DE011001000",
    "creditorId": "063997",
    "emailAddress": "Alma_Krol52@yahoo.com",
    "website": "https://adrett-laser.name/",
    "commercialClassification": false,
    "commercialRegisterNumber": "121432",
    "courtOfRegistration": "Hilden",
    "partnerAddress": {
      "postalCode": "91972",
      "city": "Nord Fabiandorf",
      "street": "Fridtjof-Nansen-Str.",
      "houseNumber": "17a",
      "poBox": "et exercitation proident",
      "addressSupplement": "veniam",
      "coSupplement": "deserunt et",
      "countryCode": "SH",
      "district": "West Miriam",
      "additionalInformation": {
        "supplement1": "in minim quis Lorem ullamco",
        "supplement2": "labore in eu sit aliqua",
        "supplement3": "in enim ipsum mollit in",
        "supplement4": "ut culpa",
        "supplement5": "nostrud culpa sint"
      }
    },
    "externalCustomerNumberSupplier": "550646",
    "externalReferences": [
      {
        "externalReferenceName": "Kundennummer beim Altlieferanten",
        "externalReferenceValue": "8019775669"
      }
    ],
    "businessPartnerRole": [
      "MARKET_PARTNER"
    ],
    "contactChannel": [
      "FAX"
    ],
    "contactPerson": {
      "boType": "CONTACT_PERSON",
      "structureVersion": "1",
      "lastName": "Rehwagen",
      "eMailAddress": "Marisa_Seelig@yahoo.com",
      "phoneNumbers": [
        {
          "numberType": "PHONE_EXTENSION",
          "phoneNumber": "(0825) 213246219"
        }
      ]
    }
  },
  "signatoryOfferRecipient": {
    "boType": "CONTACT_PERSON",
    "structureVersion": "1",
    "lastName": "Lufft",
    "eMailAddress": "Valentin_Knut60@gmail.com",
    "phoneNumbers": [
      {
        "numberType": "FAX_CENTRAL",
        "phoneNumber": "+49-720-0888487"
      }
    ]
  },
  "signatoryOfferGiver": {
    "boType": "CONTACT_PERSON",
    "structureVersion": "1",
    "lastName": "Taufratshofer",
    "eMailAddress": "Smilla48@yahoo.com",
    "phoneNumbers": [
      {
        "numberType": "DEPARTMENT_FAX",
        "phoneNumber": "+49-1305-29723414"
      }
    ]
  },
  "setupTransmissionPeriod": {
    "timeUnit": "SECOND",
    "duration": 8,
    "startDate": "1919-05-10T01:34:19.0Z",
    "endDate": "1890-09-09T07:11:48.0Z",
    "unit": "WEEK",
    "readingPeriod": "036733",
    "billingPeriod": "157720",
    "periodText": "Duis consequat non",
    "periodId": 3
  },
  "offerBindingPeriod": {
    "timeUnit": "DAY",
    "duration": 0,
    "startDate": "1894-08-20T11:25:12.0Z",
    "endDate": "1952-07-05T18:15:32.0Z",
    "unit": "MONTH",
    "readingPeriod": "807210",
    "billingPeriod": "377856",
    "periodText": "laboris",
    "periodId": 9
  },
  "variants": [
    {
      "offerStatus": "COMMISSIONED",
      "description": "culpa veniam nulla",
      "creationDate": "1961-05-14T11:14:14.0Z",
      "bindingPeriod": "1946-01-02T04:51:17.0Z",
      "totalQuantity": {
        "value": 5,
        "unit": "HOUR",
        "startDate": "1910-08-07T16:21:17.0Z",
        "endDate": "1911-01-14T19:46:18.0Z"
      },
      "totalCosts": {
        "value": 3,
        "currency": "fugiat dolor"
      },
      "parts": [
        {
          "requestSubReference": "ANSUBREF0111",
          "offerPartTotalQuantity": {
            "value": 3.75,
            "unit": "Z16",
            "startDate": "1925-12-24T04:28:56.0Z",
            "endDate": "1957-01-16T22:35:29.0Z"
          },
          "offerPartTotalCosts": {
            "value": 5.75,
            "currency": "amet velit in officia"
          },
          "deliveryPeriod": {
            "timeUnit": "HALF_YEAR",
            "duration": 9,
            "startDate": "1932-07-05T13:03:44.0Z",
            "endDate": "1902-03-04T02:34:46.0Z",
            "unit": "YEAR",
            "readingPeriod": "780103",
            "billingPeriod": "734160",
            "periodText": "commodo dolore",
            "periodId": 6
          },
          "referenceCatalogNumber": {
            "catalogNumber": "81414",
            "lineNumber": "54994",
            "versionNumber": "07308"
          },
          "deliveryPointOfferPart": [
            {
              "boType": "MARKET_LOCATION",
              "structureVersion": "1",
              "marketLocationId": "30498152858",
              "sector": "deserunt laboris occaecat",
              "energyDirection": "FEED_IN",
              "balancingMethod": "IMS",
              "consumptionType": [
                "SB"
              ],
              "interruptible": true,
              "gridLevel": "HSP",
              "transformation": "HD",
              "gridOperatorCodeNumber": "0122358950",
              "areaType": "SUPPLY_AREA",
              "gridAreaNumber": "1885008931",
              "balancingArea": "sunt elit",
              "defaultSupplierCodeNumber": "2848574305",
              "gasQuality": "H_GAS",
              "endCustomer": {
                "boType": "BUSINESS_PARTNER",
                "structureVersion": "1",
                "salutation": "Prof. Dr.",
                "name1": "Welsch",
                "name2": "Marissa",
                "name3": "cupidatat eu Duis in sed",
                "name4": "aliqua",
                "vatId": "DE101001011",
                "creditorId": "521048",
                "emailAddress": "Janis9@gmail.com",
                "website": "https://mutig-biologie.net/",
                "commercialClassification": false,
                "commercialRegisterNumber": "306564",
                "courtOfRegistration": "Kempten (Allgäu)",
                "partnerAddress": {
                  "postalCode": "02188",
                  "city": "Leneland",
                  "street": "Im Eisholz",
                  "houseNumber": "33",
                  "poBox": "dolor eiusmod aliquip ut id",
                  "addressSupplement": "officia occaecat velit veniam ex",
                  "coSupplement": "Ut commodo cillum do",
                  "countryCode": "SZ",
                  "district": "Juanstadt",
                  "additionalInformation": {
                    "supplement1": "dolore ullamco tempor magna mollit",
                    "supplement2": "irure",
                    "supplement3": "anim culpa nisi aliquip",
                    "supplement4": "irure",
                    "supplement5": "officia"
                  }
                },
                "externalCustomerNumberSupplier": "571232",
                "externalReferences": [
                  {
                    "externalReferenceName": "Kundennummer beim Lieferanten",
                    "externalReferenceValue": "7580919305"
                  }
                ],
                "businessPartnerRole": [
                  "SUPPLIER"
                ],
                "contactChannel": [
                  "PHONE_CALL"
                ],
                "contactPerson": {
                  "boType": "CONTACT_PERSON",
                  "structureVersion": "1",
                  "lastName": "Tepper",
                  "eMailAddress": "Jeremy.Blassneck@gmail.com",
                  "phoneNumbers": [
                    {
                      "numberType": "MOBILE_NUMBER",
                      "phoneNumber": "(0742) 310218848"
                    }
                  ]
                }
              },
              "locationAddress": {
                "postalCode": "07388",
                "city": "West Naemistadt",
                "street": "Gustav-Heinemann-Str.",
                "houseNumber": "9",
                "poBox": "labore adipisicing cupidatat",
                "addressSupplement": "pariatur reprehenderit dolor Ut eu",
                "coSupplement": "Lorem in dolore nostrud tempor",
                "countryCode": "PY",
                "district": "Oliverscheid",
                "additionalInformation": {
