=== conuti-gmbh/bo4e-schema-en/schemas/v1/bo/Order.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema/master/schemas/v1/bo/Auftrag.schema.json",
  "title": "Order",
  "type": "object",
  "properties": {
    "boType": {
      "$ref": "../enum/BOType.schema.json",
      "default": "ORDER"
    },
    "structureVersion": {
      "type": "string",
      "default": "1",
      "description": "versionStruktur"
    },
    "executionDate": {
      "type": "string",
      "format": "date-time",
      "description": "Das Ausführungsdatum beschreibt zu welchem Zeitpunkt ein Auftrag ausgeführt werden soll."
    },
    "completionDate": {
      "type": "string",
      "format": "date-time",
      "description": "Das Fertigstellungsdatum beschreibt zu welchem Zeitpunkt ein Auftrag ausgeführt wurde/wird."
    },
    "startDate": {
      "type": "string",
      "format": "date-time",
      "description": "Das Startdatum beschreibt zu welchem Zeitpunkt ein Auftrag gestartet wurde/wird."
    },
    "endDate": {
      "type": "string",
      "format": "date-time",
      "description": "Das Enddatum beschreibt zu welchem Zeitpunkt ein Auftrag endete oder enden wird."
    },
    "sector": {
      "$ref": "../enum/Sector.schema.json",
      "description": "Die Sparte in der der Auftrag relevant ist"
    },
    "deliveryAddress": {
      "$ref": "../com/Address.schema.json",
      "description": "Die Adresse, die sich in Belieferung befindet."
    },
    "marketLocationId": {
      "type": "string",
      "faker": {
        "string.numeric": 11
      },
      "description": "Die ID der Marktlokation der der zu sperrende Zähler zugeordnet ist."
    },
    "minimumPrice": {
      "$ref": "../com/Price.schema.json",
      "description": "Der Mindestpreis eines Auftrags (z.B. für eine Sperrung)"
    },
    "maximumPrice": {
      "$ref": "../com/Price.schema.json",
      "description": "Der Höchstpreis eines Auftrags (z.B. für eine Sperrung)"
    },
    "energyDirection": {
      "$ref": "../enum/EnergyDirection.schema.json"
    },
    "calculationPrice": {
      "type": "number",
      "format": "float",
      "faker": {
        "number.float": {
          "multipleOf": 0.25,
          "min": 1,
          "max": 10
        }
      },
      "description": "berechnungspreis"
    },
    "totalSum": {
      "type": "number",
      "format": "float",
      "faker": {
        "number.float": {
          "multipleOf": 0.25,
          "min": 10,
          "max": 20
        }
      },
      "description": "summeGesamt"
    },
    "postponedDeregistrationDate": {
      "type": "string",
      "format": "date-time",
      "description": "verschobenerAbmeldetermin"
    },
    "resolutionTimestamp": {
      "type": "string",
      "format": "date-time",
      "description": "behebungsZeitpunkt"
    },
    "deliveryAddressOldDevices": {
      "$ref": "../bo/BusinessPartner.schema.json"
    },
    "definitionType": {
      "$ref": "../enum/DefinitionType.schema.json"
    },
    "positionData": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "../com/OrderPosition.schema.json"
      },
      "description": "positionsdaten"
    },
    "remarks": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "string",
        "faker": {
          "lorem.sentence": 5
        }
      },
      "description": "bemerkungen"
    }
  },
  "required": [
    "boType",
    "structureVersion"
  ]
}

=== conuti-gmbh/bo4e-schema-en/docs/examples/bo/Order.json
{
  "boType": "ORDER",
  "structureVersion": "1",
  "executionDate": "1932-03-27T06:33:39.0Z",
  "completionDate": "1894-04-29T20:43:18.0Z",
  "startDate": "1890-10-29T16:03:11.0Z",
  "endDate": "1897-07-03T11:10:01.0Z",
  "sector": "ELECTRICITY",
  "deliveryAddress": {
    "postalCode": "05295",
    "city": "West Amelie",
    "street": "Scharnhorststr.",
    "houseNumber": "29",
    "poBox": "sit dolore quis incididunt laborum",
    "addressSupplement": "elit consectetur Ut",
    "coSupplement": "ipsum do ullamco sed est",
    "countryCode": "PK",
    "district": "Eisenlauerburg",
    "additionalInformation": {
      "supplement1": "consectetur irure mollit",
      "supplement2": "sint deserunt",
      "supplement3": "in tempor Ut aute velit",
      "supplement4": "cupidatat",
      "supplement5": "cupidatat in"
    }
  },
  "marketLocationId": "52024397344",
  "minimumPrice": {
    "value": 6.25,
    "amount": 92412558,
    "minimumAmount": 8,
    "maximumAmount": 2,
    "unit": "EUR",
    "referenceValue": "HOUR",
    "status": "PROVISIONAL",
    "priceType": "SETUP_PRICE"
  },
  "maximumPrice": {
    "value": 4.75,
    "amount": 45178987,
    "minimumAmount": 2,
    "maximumAmount": 4,
    "unit": "EUR",
    "referenceValue": "COUNT",
    "status": "FINAL",
    "priceType": "OPERATING_PRICE"
  },
  "energyDirection": "FEED_OUT",
  "calculationPrice": 1,
  "totalSum": 12.5,
  "postponedDeregistrationDate": "1899-08-06T02:28:56.0Z",
  "resolutionTimestamp": "1953-02-13T23:21:38.0Z",
  "deliveryAddressOldDevices": {
    "boType": "BUSINESS_PARTNER",
    "structureVersion": "1",
    "salutation": "Prof. Dr.",
    "name1": "Elbe",
    "name2": "Emmi",
    "name3": "sed non nulla eu",
    "name4": "Excepteur sunt",
    "vatId": "DE110110000",
    "creditorId": "648131",
    "emailAddress": "Danny7@yahoo.com",
    "website": "https://kunstvoll-automobil.com",
    "commercialClassification": true,
    "commercialRegisterNumber": "670525",
    "courtOfRegistration": "Mirjaburg",
    "partnerAddress": {
      "postalCode": "18523",
      "city": "Oseidorf",
      "street": "An der Steinrütsch",
      "houseNumber": "59a",
      "poBox": "dolore Duis minim reprehenderit Excepteur",
      "addressSupplement": "mollit",
      "coSupplement": "commodo",
      "countryCode": "RW",
      "district": "Ahlen",
      "additionalInformation": {
        "supplement1": "et sit anim nisi",
        "supplement2": "magna nulla Excepteur enim",
        "supplement3": "cupidatat velit",
        "supplement4": "aliquip",
        "supplement5": "adipisicing ex labore quis"
      }
    },
    "externalCustomerNumberSupplier": "807375",
    "externalReferences": [
      {
        "externalReferenceName": "Kundennummer beim Lieferanten",
        "externalReferenceValue": "3284678206"
      }
    ],
    "businessPartnerRole": [
      "CUSTOMER"
    ],
    "contactChannel": [
      "EMAIL"
    ],
    "contactPerson": {
      "boType": "CONTACT_PERSON",
      "structureVersion": "1",
      "lastName": "Koob",
      "eMailAddress": "Juliana.Bornscheuer@hotmail.com",
      "phoneNumbers": [
        {
          "numberType": "COLLECTIVE_FAX",
          "phoneNumber": "+49-9158-50626616"
        }
      ]
    }
  },
  "definitionType": "METERING_TIME",
  "positionData": [
    {
      "positionNumber": 85277572,
      "offerPositionNumber": "043066",
      "energyCapture": "CAPTURED_SEPARATELY",
      "articleNumber": "CONCESSION_FEE",
      "positionAmount": "83",
      "validFrom": "1969-08-29T09:17:55.0Z",
      "startDate": "1893-08-15T04:35:52.0Z",
      "endDate": "1943-01-14T01:16:14.0Z",
      "isExisting": "0",
      "obisNumber": "nostrud Duis Lorem id",
      "requestReason": "INTERIM_READING",
      "generalInformation": {
        "info1": "ea dolor sit sint elit",
        "info2": "ut fugiat do irure id",
        "info3": "do aliquip mollit sed",
        "info4": "in Duis ad",
        "info5": "exercitation aliquip amet culpa"
      },
      "discrepancyInfo": {
        "discrepancy1": "id aute tempor mollit",
        "discrepancy2": "in non tempor",
        "discrepancy3": "dolor",
        "discrepancy4": "nostrud ipsum",
        "discrepancy5": "pariatur dolore"
      },
      "definitionType": "LOAD_CURVES",
      "locationId": "47864748907",
      "meterRegister": 2,
      "endpointAddress": {
        "gwaManagement": "officia qui dolor",
        "gwaAdminService": "dolore officia cillum fugiat aliquip",
        "gwaNTP": "ullamco culpa elit pariatur"
      },
      "certificateInformation": {
        "uriSubCA": "velit",
        "commonNameCertificate": "occaecat",
        "serialNumberCertificate": "aliquip Ut in"
      },
      "wakeUpPort": "veniam ullamco ea non elit",
      "apnCommunicationData": "Duis nisi eu ut elit"
    }
  ],
  "remarks": [
    "Ut amet sint maiores iure."
  ]
}
