=== conuti-gmbh/bo4e-schema-en/schemas/v1/bo/StatusNotification.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema-en/main/schemas/v1/bo/StatusNotification.schema.json",
  "title": "StatusNotification",
  "type": "object",
  "properties": {
    "boType": {
      "$ref": "../enum/BOType.schema.json",
      "default": "STATUS_NOTIFICATION"
    },
    "structureVersion": {
      "type": "string",
      "default": "1"
    },
    "statusObject": {
      "$ref": "../enum/StatusObject.schema.json"
    },
    "statusOccasion": {
      "$ref": "../enum/Status.schema.json"
    },
    "orderStatus": {
      "$ref": "../enum/OrderStatus.schema.json"
    },
    "positionData": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "../com/StatusNotificationPosition.schema.json"
      }
    }
  },
  "required": [
    "boType",
    "structureVersion"
  ]
}

=== conuti-gmbh/bo4e-schema-en/docs/examples/bo/StatusNotification.json
{
  "boType": "STATUS_NOTIFICATION",
  "structureVersion": "1",
  "statusObject": "UNLOCK",
  "statusOccasion": "REPLACEMENT_OF_SUBSTITUTE_VALUE",
  "orderStatus": "ENFG_PRODUCTION_OF_GREEN_HYDROGEN",
  "positionData": [
    {
      "positionNumber": 6,
      "processingDate": "1895-02-24T19:16:01.0Z",
      "usageFrom": "1963-04-08T19:38:29.0Z",
      "usageTo": "1959-04-02T16:32:22.0Z",
      "endDate": "1917-06-13T01:53:21.0Z",
      "orderStatus": "ENFG_ELECTRICALLY_DRIVEN_HEAT_PUMPS",
      "statusOccasion": "NO_FAULT_DETECTABLE",
      "responseStatus": "veniam in ad",
      "errorDescription": {
        "description1": "aliqua dolor nulla",
        "description2": "ipsum Ut",
        "description3": "elit magna do deserunt pariatur",
        "description4": "Duis laboris reprehenderit",
        "description5": "reprehenderit ex consectetur ut cupidatat"
      },
      "errorDescriptionText": "reprehenderit occaecat irure do ipsum",
      "justification": {
        "justification1": "in",
        "justification2": "in aliquip culpa mollit",
        "justification3": "dolore dolore",
        "justification4": "occaecat",
        "justification5": "incididunt enim exercitation"
      },
      "justificationText": "quis consectetur incididunt",
      "locationId": "43869841365",
      "referenceMelo": "723622266392430189387875166841114",
      "generalInformation": {
        "info1": "enim nulla ex esse",
        "info2": "laboris adipisicing",
        "info3": "velit ut labore in veniam",
        "info4": "non sunt qui veniam ea",
        "info5": "quis consequat"
      },
      "generalInformationText": "in voluptate",
      "statusChangeTimestamp": "1931-09-30T08:05:37.0Z",
      "orderStatusList": [
        "ENFG_ELECTRICALLY_OPERATED_BUSES_IN_SCHEDULED_SERVICE"
      ],
      "locationType": "CONTROLLABLE_RESOURCE",
      "statusObject": "DEVICE",
      "responseStatusCodeList": "velit",
      "processReferenceNumber": "non",
      "notificationNumber": "ex do esse dolor fugiat",
      "requestReferenceNumber": "Ut qui irure",
      "completionDate": "1954-04-08T22:02:23.0Z",
      "deliveryDate": "pariatur esse officia veniam ex",
      "shipmentPosition": 59753847,
      "validFrom": "1927-04-06T11:43:55.0Z",
      "referenceMalo": "consectetur exercitation irure nulla",
      "referencePriceKeyMaster": "officia in esse",
      "referenceArticleId": "laboris",
      "startDate": "1892-10-16T13:01:42.0Z",
      "offerNumber": "nostrud pariatur",
      "inquiryReference": "ea consectetur dolore",
      "contractEnd": "1957-04-11T04:19:14.0Z",
      "runningNumber": 5,
      "documentReferenceNumber": "fugiat dolor non sit cupidatat",
      "senderView": [
        {
          "usageFrom": "1934-11-13T11:41:25.0Z",
          "usageTo": "1969-04-18T04:37:32.0Z",
          "servicePeriod": "nisi",
          "amount": {
            "value": 1.75,
            "unit": "HOUR",
            "startDate": "1966-12-05T11:17:57.0Z",
            "endDate": "1894-08-20T05:43:58.0Z"
          },
          "tariffLevel": "TARIFF_LEVEL_5"
        }
      ],
      "validityTimespan": "pariatur esse",
      "privilegedEnergyQuantity": {
        "usageFrom": "1925-05-22T13:14:26.0Z",
        "usageTo": "1926-12-06T15:18:15.0Z",
        "amount": {
          "value": 5,
          "unit": "VARH",
          "startDate": "1921-03-29T21:43:47.0Z",
          "endDate": "1899-07-22T16:37:54.0Z"
        }
      },
      "contactPerson": {
        "boType": "CONTACT_PERSON",
        "structureVersion": "1",
        "lastName": "Gutowicz",
        "eMailAddress": "Abby92@hotmail.com",
        "phoneNumbers": [
          {
            "numberType": "COLLECTIVE_PHONE",
            "phoneNumber": "+49-3274-34984258"
          }
        ]
      },
      "timeSeriesVersion": "commodo non eu adipisicing magna",
      "balancingStart": "1945-01-25T08:36:37.0Z"
    }
  ]
}
