=== conuti-gmbh/bo4e-schema-en/schemas/v1/bo/ValuesByType2.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema-en/main/schemas/v1/bo/ValuesByType2.schema.json",
  "title": "ValuesByType2",
  "type": "object",
  "properties": {
    "boType": {
      "$ref": "../enum/BOType.schema.json",
      "default": "VALUES_BY_TYPE2"
    },
    "structureVersion": {
      "type": "string",
      "default": "1"
    },
    "configurationProduct": {
      "type": "string"
    },
    "meteringProduct": {
      "type": "string"
    },
    "targetAddress": {
      "$ref": "../com/TargetAddress.schema.json"
    },
    "issuer": {
      "$ref": "../com/Issuer.schema.json"
    },
    "certificateUser": {
      "$ref": "../com/CertificateUser.schema.json"
    },
    "configurationChangeOption": {
      "$ref": "../enum/ConfigurationChangeOption.schema.json"
    },
    "thresholds": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "../com/Threshold.schema.json"
      }
    },
    "meterRegisters": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "../com/MeterRegister.schema.json"
      }
    }
  },
  "required": [
    "boType",
    "structureVersion"
  ]
}

=== conuti-gmbh/bo4e-schema-en/docs/examples/bo/ValuesByType2.json
{
  "boType": "VALUES_BY_TYPE2",
  "structureVersion": "1",
  "configurationProduct": "velit consectetur culpa nisi",
  "meteringProduct": "esse cupidatat minim",
  "targetAddress": {
    "targetAddress1": "cupidatat ea",
    "targetAddress2": "qui eiusmod quis Excepteur",
    "targetAddress3": "culpa id proident",
    "targetAddress4": "cupidatat eu incididunt sunt",
    "targetAddress5": "veniam"
  },
  "issuer": {
    "issuer1": "est dolor anim",
    "issuer2": "nostrud dolor nisi nulla",
    "issuer3": "esse elit Duis",
    "issuer4": "sint aute",
    "issuer5": "eu esse aute"
  },
  "certificateUser": {
    "certificateUser1": "amet quis",
    "certificateUser2": "sed Lorem cillum dolore",
    "certificateUser3": "velit",
    "certificateUser4": "ullamco non consectetur pariatur est",
    "certificateUser5": "qui in"
  },
  "configurationChangeOption": "REQUIRED",
  "thresholds": [
    {
      "upperThreshold": 14.5,
      "lowerThreshold": 3,
      "configurationProduct": "KONF_0010"
    }
  ],
  "meterRegisters": [
    {
      "meterRegisterId": "102690316",
      "designation": "aliquip aliqua",
      "direction": "FEED_OUT",
      "obisCode": "esse Duis ut",
      "transformerFactor": 4.5,
      "unit": "HOUR",
      "offPeakCapable": "OFF_PEAK_CAPABLE",
      "consumptionType": [
        "SB"
      ],
      "interruptibility": "NUV",
      "heatUsage": "HEAT_PUMP_HEATING",
      "concessionFee": {
        "rate": "TKS",
        "costs": -92514257.18452193,
        "category": "aliquip laboris sed ipsum non"
      },
      "taxExempt": true,
      "integerDigits": 9,
      "decimalPlaces": 8,
      "billingRelevant": false,
      "numberOfReadings": 2,
      "meteringTimes": {
        "register": "sint quis sunt",
        "meteringTimeDefinition": "ea amet",
        "offPeakCapable": "NOT_OFF_PEAK_CAPABLE"
      },
      "configuration": "Ut irure",
      "meteringProduct": "ad dolor",
      "valueGranularity": "MONTHLY",
      "necessitySecondMeasurement": "NOT_PRESENT",
      "valueTransmissionPurpose": "PRESENT",
      "typeElectricMobility": "WB",
      "configurationProduct": "ipsum aliquip cillum occaecat tempor",
      "noConfigurationProduct": true,
      "loadCurveDefinition": "exercitation dolor Excepteur aliquip dolor",
      "purposesOfUse": [
        {
          "marketRole": "MDL",
          "purpose": [
            "REACTIVE_ENERGY_BILLING_OPERATIONS_MANAGEMENT"
          ]
        }
      ],
      "usagePurposeNB": "pariatur eiusmod laborum est do",
      "usagePurposeLF": "ullamco est ipsum anim",
      "usagePurposeUENB": "aute nostrud",
      "noProduct": false
    }
  ]
}
